### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by OtsukiMana-2003tech** [OtsukiMana-2003tech/protospace-40808#1]
## ProtoSpace-40808の実装完了および挙動確認の依頼

ProtoSpaceの実装が完了いたしました。つきましては、ProtoSpaceの挙動確認をお願いいたします。
以下のURLにProtoSpace-40808にアクセスするためのURLを共有いたします。ご査収のほどよろしくお願いいたします。

URL：https://protospace-40808.onrender.com

**Comment by Katsuno0814** [comment]
[OtsukiMana-2003tech](https://github.com/OtsukiMana-2003tech)さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
プロトタイプ編集機能 
- [x]  正しく編集できた場合は、詳細ページへ遷移すること
こちら現状詳細ページではなくトップページへ遷移してしまいますので修正お願いいたします。

プロトタイプ削除機能
- [x]  ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できること
こちら削除を行いますとエラー画面が表示されてしまいますので、削除を行えるように修正お願いいたします。
![スクリーンショット 2024-05-28 13 22 41](https://github.com/OtsukiMana-2003tech/protospace-40808/assets/62652429/8c7d9aa7-931b-408f-86ae-5549cbc5a11d)






修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。

**Comment by Katsuno0814** [comment]
@OtsukiMana-2003tech さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
